### ISSUE TITLE
RFC: Update image names to reference devtoolset or gcc version

### ISSUE THREAD

**Issue by jcfr** [dockbuild/dockbuild#29]
Currently `dockbuild/centos6:latest` includes `devtoolset-2` but [some project](https://github.com/Slicer/SlicerBuildEnvironment/commit/8e63e1fa2206c11c02abecbac5a3b9ac97fa98ef) can also require `devtoolset-3`, what should be the name of our dockbuild images;

```
dockbuild/centos6:latest                          # default is devtoolset2
dockbuild/centos6devtoolset3:latest
```

or consistently rename all images as such (my preferred approach): 

```
dockbuild/devtoolset2-centos5:latest
dockbuild/devtoolset2-centos6:latest                  
dockbuild/devtoolset3-centos6:latest
dockbuild/devtoolset4-centos7:latest

dockbuild/gcc44-ubuntu1004:latest
dockbuild/gcc54-ubuntu1604:latest
dockbuild/gcc73-ubuntu1804:latest
```

Cc: @thewtex  @jjcf89

**Comment by jcfr** [comment]
The centos image could also be more explicit with:

```
dockbuild/gcc48-devtoolset2-centos5:latest
dockbuild/gcc48-devtoolset2-centos6:latest                  
dockbuild/gcc49-devtoolset3-centos6:latest
dockbuild/gcc53-devtoolset4-centos7:latest
```

but I  think it is simpler to stick with the `devtoolset` and point to the relevant devtoolset documentation.

**Comment by thewtex** [comment]
+1

Also, I think it is nice to go from common to specific for sorting purposes, i.e. `dockbuild/centos6-devtoolset2-gcc48`

**Comment by jcfr** [comment]
Thanks for the feedback. I will incorporate this change

**Comment by jcfr** [comment]
For consistency, I am thinking to go with this layout (where gccXY comes before the devtoolsetN)

```
dockbuild/centos5-gcc48-devtoolset2:latest
dockbuild/centos6-gcc48-devtoolset2:latest                  
dockbuild/centos6-gcc49-devtoolset3:latest
dockbuild/centos7-gcc53-devtoolset4:latest

dockbuild/ubuntu1004-gcc44:latest
dockbuild/ubuntu1604-gcc54:latest
dockbuild/ubuntu1804-gcc73:latest
```

**Comment by jcfr** [comment]
Thanks everyone for the feedback, changes have been implemented in https://github.com/dockbuild/dockbuild/pull/31

To maintain backward compat for existing images depending on dockbuild (I already have few), orginal images will still be pushed.

For reference, here is what we have:

```
centos5-devtoolset2-gcc4
centos6-devtoolset2-gcc4
centos7-devtoolset4-gcc5

ubuntu1004-gcc4
ubuntu1604-gcc5
ubuntu1804-gcc7

# Here to maintain backward compat with existing images depending on dockbuild:
centos5
centos6
centos7

ubuntu1004
ubuntu1604
ubuntu1804
```

**Comment by jcfr** [comment]
Closing. Changes integrated in https://github.com/dockbuild/dockbuild/commit/5768a271712e2197f2f97efd2b98c6ee35fd2efa
