### ISSUE TITLE
Evaluate transition to GitHub action

### ISSUE THREAD

**Issue by jcfr** [dockbuild/dockbuild#69]
See https://github.com/dockcross/dockcross/blob/master/.github/workflows/main.yml

**Comment by jcfr** [comment]
@thewtex @JonasVautherin For each dockcross images, are we pushing on dockhub both the `latest` and `YYYYMMDD-SHA{7}` tag ?

**Comment by JonasVautherin** [comment]
It's just doing `docker image push dockcross/${{ matrix.arch_name }}` (which for `android-arm` would be `docker image push dockcross/android-arm`).

I must say I don't know exactly how that works internally, e.g. does it actively push a `latest` tag, or does the server move the `latest` cursor whenever a new image is pushed? I would intuitively think about the latter, but I don't know :smile:

**Comment by thewtex** [comment]
By default, Docker pushes to the `latest` tag

We will have to re-add pushes of the date-sha tags.

**Comment by JonasVautherin** [comment]
@thewtex: it seems to me that the date tags are pushed: 

```
20210210-84c47e5
Last pushed a month ago by dockcrossci
```

I did not push them manually, so it has to come from the CI, right?

**Comment by thewtex** [comment]
@JonasVautherin do you have a link for this?

When I check here:

https://hub.docker.com/r/dockcross/base/tags?page=1&ordering=last_updated

I get only get an updated `latest`:

![image](https://user-images.githubusercontent.com/25432/110843689-93a8d800-8276-11eb-9417-61ca6487cf9b.png)

**Comment by JonasVautherin** [comment]
This one from @jcfr message above: https://hub.docker.com/r/dockcross/manylinux2014-x64/tags?page=1&ordering=last_updated

But you're right, dockcross/base is not... :thinking:

**Comment by thewtex** [comment]
> EDIT: and actually that would answer the initial question laughing. The tag is made by the Makefile, and docker push image pushes both tags. Would that make sense?

Yes! Thanks for the follow-up -- looks like we are in good shape :muscle: .

**Comment by thewtex** [comment]
> EDIT: and actually that would answer the initial question laughing. The tag is made by the Makefile, and docker push image pushes both tags. Would that make sense?

Yes, thanks @JonasVautherin for the investigation.
